### ISSUE TITLE
Error when compiling with mingw32

### ISSUE THREAD

**Issue by Moosieus** [Rhoban/Plater#1]

**Comment by Gregwar** [comment]
Hello @Moosieus 
Did you find a solution to your problem?

**Comment by Moosieus** [comment]
Yeah, I just added the source files directly into visual studio, replaced a
few headers, and it worked. I got rid of my issue report because I felt
like it wasn't an issue with the code, so much as my own ignorance.

On Fri, Sep 30, 2016 at 9:57 AM, Grégoire Passault <notifications@github.com

**Comment by Gregwar** [comment]
Anyway, if you think that your fiddling desserves documentation or minor tweaks to get it compiling with Visual Studio do not hesitate to share

**Comment by Gregwar** [comment]
My own build (that is available as binaries as in the README) were done using a Qt+MinGW prebuild kit I got
