### ISSUE TITLE
Feature Request: add circular bed support

### ISSUE THREAD

**Issue by brandonheller** [Rhoban/Plater#11]
I love the idea of Plater, but all my printers are deltas with circular beds.  With that shape, dense plating is much harder, so plater would have even more value there.   

Is this a big change?  Might give it a try if you can point me to the right place.  Thanks.

**Comment by Gregwar** [comment]
Hello
It is already there
You can enable circular bed in settings screen

**Comment by brandonheller** [comment]
I can't see that option (which I now see in the demo video) on the Mac v1.0.0 download.  The issue might be that the file there shows a modified date of Jun 5, 2014, so I have to imagine it's old - despite the release on GitHub showing an update 17 days ago.  Here's what I see on the Setting page:
![image](https://user-images.githubusercontent.com/82859/79272976-0dfa8d80-7e57-11ea-967a-58909161c8e0.png)
 
Any ideas?  Itching to try to be able to print more PPE.  Thanks!

**Comment by Gregwar** [comment]
Should be like this:

![image](https://user-images.githubusercontent.com/367022/79275312-3bbaf300-7ea6-11ea-8058-c8c8a70b0bac.png)

Actually, I have no way to build MAC OS version, because I don't have access to a Mac anytime soon, the better is for you to compile it from sources I guess, is that feasible?

**Comment by brandonheller** [comment]
I was able to built it from source, with:

```
brew install cmake
brew install qt
brew link qt5 --force
```

Seems to work!  Thanks.   I'll add some things I noticed that would be amazing to fix.
