### ISSUE TITLE
Feature Request: Show circular bed as circular

### ISSUE THREAD

**Issue by brandonheller** [Rhoban/Plater#12]
When using the circular bed option with many parts, you can see them in the rectangular grid forming a circular outline, but it's hard to see how close to the edge you are, which might help with really packing things in.  

The request is to show (in the plater view, once the plating has been found) the circular bed outline when this option is used.

**Comment by Gregwar** [comment]
Just pushed in master, can you check it out?

**Comment by Gregwar** [comment]
![image](https://user-images.githubusercontent.com/367022/79434332-83d53500-7fce-11ea-87a8-a2a766a1f187.png)
