### ISSUE TITLE
Setting threads count

### ISSUE THREAD

**Issue by mateuszbrzezinski** [Rhoban/Plater#18]
Please add option to set threads num in GUI

**Comment by Gregwar** [comment]
Hello,
This is already there:

![image](https://user-images.githubusercontent.com/367022/88918810-602ab780-d26a-11ea-8202-24090a666570.png)

**Comment by mateuszbrzezinski** [comment]
No, it is not there
![Screenshot 2020-07-30 at 13 44 38](https://user-images.githubusercontent.com/1177739/88919183-f828a100-d26a-11ea-9ed4-ccaa8a7fc128.png)

**Comment by Gregwar** [comment]
Ok, I belive you are running the v1.0 dmg on MAC then?
Actually I have no way to make a dmg myself so you can consider building from source or repackaging it
