### ISSUE TITLE
not possible to place parts that exceed the bed size diagonally.

### ISSUE THREAD

**Issue by herexx6349** [Rhoban/Plater#19]
Hi,
i wanted to place legolini (https://legolini.com/files/Legolini_STL.7z) parts on a 300mm bed, which unfortunately does not work although the long parts would fit diagonally.

```
`$ size=300 && ~/Plater-master/plater/build/plater -v -W $size -H $size -j 0.5 -s 0.5 -d 0.5 -r 45 -S -R 1 -t 8 -o "packed${size}plate%01d" plater.conf 
* Reading from plater.conf
- Loading combined_german_magazine_part1+2.stl (quantity 1, orientation bottom)...
! Can't process: Part combined_german_magazine_part1+2.stl is too big for the plate`
```

**Comment by Gregwar** [comment]
Hello,
I fixed that on master
Now if only some orientation can work for a part, they will be kept and only those ones will be tried

Can you tell me if it works for you?

**Comment by herexx6349** [comment]
Works great for me, thanks!
