### ISSUE TITLE
Sorted models info

### ISSUE THREAD

**Issue by jakub-shaperobotics** [Rhoban/Plater#2]
Hi,
Is there a way to know which models go to which plate after sorting via Plater? I'm trying to keep a tab on my prints while printing them optimally and Plater has been a huge help.

**Comment by Gregwar** [comment]
Hey
You mean producing an output file or log with, for each plate the models on it right?

**Comment by jakub-shaperobotics** [comment]
Yes, exactly.

**Comment by Gregwar** [comment]
I added an option to output a `plates.csv` file containing infos about the plates

Are you able to recompile Plater or do you need me to produce a new zip release?

**Comment by jakub-shaperobotics** [comment]
Works like a charm. Thank you!
