### ISSUE TITLE
Plater width, height and what about length?

### ISSUE THREAD

**Issue by ipepe** [Rhoban/Plater#3]
Hey @Rhoban
I am using plater on our printer, and printing bed base is not squared. It's dimensions are: 

X(width)=200mm Y(length)=250mm Z(height)=210mm

But we cannot specify length in command line. But in GUI version of plater there are two boxes that seem to specify width and length but not height.

Could You clarify on that?

**Comment by Gregwar** [comment]
Actually, the width and the height specify the dimension of the plate, but the Z dimension cannot be specified in Plater

So you should use `-W 200 -H 250` using the command line

**Comment by Gregwar** [comment]
(Since you specify yourself the part orientation we assume that you also check that it is possible for the parts to be printed in this orientation regarding the Z-axis)

**Comment by ipepe** [comment]
Ok, so basically by Height You mean Length?
![diagram](https://upload.wikimedia.org/wikipedia/commons/8/88/Height_demonstration_diagram.png)
If so, it would be nice to note it somewhere in readme and commandline help.
