### ISSUE TITLE
Saving Settings/Advanced tab

### ISSUE THREAD

**Issue by eried** [Rhoban/Plater#4]
Hi, this tool is awesome! is there any way to save the settings in the Windows version?

**Comment by Gregwar** [comment]
Hello,
Unfortunately this is not possible using the GUI
One  current solution is to use the command line tool, maybe along with some `.bat` to run it with one click

Another one would be to change the app to add such a feature
Maybe writing some code to export/import settings to some files using suppose JsonCPP would be not that long work to do

**Comment by Gregwar** [comment]
OK, I added an option to save and load configuration from `config.json` (in same folder as executable)
It is loaded on startup so you can just click file > save config.json and it will be loaded again after next startup

**Comment by eried** [comment]
Awesome! Thanks! I was trying to setup QT Creator, but without experience into that environment it looked like a lot of fiddling.

**Comment by eried** [comment]
Oh, there is missing files in 1.1 

![image](https://user-images.githubusercontent.com/1091420/56133779-949f3500-5f8d-11e9-9ee3-a3ab941a0175.png)
(Also another one with *thread*.dll name)

**Comment by Gregwar** [comment]
Hello, I updated the binaries and it should be ok now

**Comment by Gregwar** [comment]
(Be sure your browser indeed re-download the updated file: http://gregwar.com/plater/plater-win32-1.1.zip?2)

**Comment by Gregwar** [comment]
Is it ok ?

**Comment by eried** [comment]
Yes! it is perfect. Thanks a lot, great utility
